language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  # Not necessary, but good to check that they work.
  - npm run load-db
  - npm run drop-db
  # We don't run dump-db to avoid dirtying our local checkout, leading
  # to confusing test results.
script:
  - cd src/backend && istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
after_success:
  # FIXME: taken from the docs at https://www.npmjs.com/package/coveralls,
  # but this is a pointless use of cat.
  - cd src/backend && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
