language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
services:
  - mongodb
before_script:
  # TODO: we should do everything from our package.json, as this may
  # install newer versions than we wanted.
  - npm install -g istanbul
  - npm install -g mocha

  # Not necessary, but good to check that they work.
  - npm run load-db
  - npm run drop-db
  # We don't run dump-db to avoid dirtying our local checkout, leading
  # to confusing test results.
script:
  # backend tests
  - cd src/backend
  - istanbul cover _mocha --report lcovonly -- -R spec
  - cd ../..

  # ensure we can load the frontend
  - export PATH=$PATH:node_modules/.bin
  - npm run load-db
  - phantomjs src/frontend/test/test_homepage_loads.js
after_success:
  # FIXME: taken from the docs at https://www.npmjs.com/package/coveralls,
  # but this is a pointless use of cat.
  - cat src/backend/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
