language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  # Not necessary, but good to check that they work.
  - npm run load-db
  - npm run drop-db
  # We don't run dump-db to avoid dirtying our local checkout, leading
  # to confusing test results.
script:
  - npm run test
